using System;
using AFHSync.Shared.Enums;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace AFHSync.Api.Migrations
{
    /// <inheritdoc />
    public partial class MultiSourcePerTunnel : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: production DB may already have these changes applied.
            // Use raw SQL with IF EXISTS / IF NOT EXISTS guards.

            // Drop seed data rows if they still exist
            migrationBuilder.Sql("DELETE FROM tunnels WHERE id IN (1,2,3,4,5,6) AND EXISTS (SELECT 1 FROM tunnels WHERE id = 1);");

            // Drop columns only if they exist
            migrationBuilder.Sql("ALTER TABLE tunnels DROP COLUMN IF EXISTS source_display_name;");
            migrationBuilder.Sql("ALTER TABLE tunnels DROP COLUMN IF EXISTS source_filter_plain;");
            migrationBuilder.Sql("ALTER TABLE tunnels DROP COLUMN IF EXISTS source_identifier;");
            migrationBuilder.Sql("ALTER TABLE tunnels DROP COLUMN IF EXISTS source_smtp_address;");
            migrationBuilder.Sql("ALTER TABLE tunnels DROP COLUMN IF EXISTS source_type;");

            // Create tunnel_sources table only if it doesn't exist
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS tunnel_sources (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tunnel_id integer NOT NULL REFERENCES tunnels(id) ON DELETE CASCADE,
                    source_type source_type NOT NULL,
                    source_identifier character varying(2000) NOT NULL,
                    source_display_name character varying(200),
                    source_smtp_address character varying(320),
                    source_filter_plain character varying(2000),
                    created_at timestamp with time zone NOT NULL DEFAULT NOW()
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS idx_tunnel_sources_tunnel_id
                ON tunnel_sources (tunnel_id);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "tunnel_sources");

            migrationBuilder.AddColumn<string>(
                name: "source_display_name",
                table: "tunnels",
                type: "character varying(200)",
                maxLength: 200,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "source_filter_plain",
                table: "tunnels",
                type: "character varying(500)",
                maxLength: 500,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "source_identifier",
                table: "tunnels",
                type: "character varying(500)",
                maxLength: 500,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "source_smtp_address",
                table: "tunnels",
                type: "character varying(320)",
                maxLength: 320,
                nullable: true);

            migrationBuilder.AddColumn<SourceType>(
                name: "source_type",
                table: "tunnels",
                type: "source_type",
                nullable: false,
                defaultValue: SourceType.Ddg);

            migrationBuilder.InsertData(
                table: "tunnels",
                columns: new[] { "id", "field_profile_id", "name", "photo_sync_enabled", "source_display_name", "source_filter_plain", "source_identifier", "source_smtp_address", "source_type", "stale_hold_days", "stale_policy", "status" },
                values: new object[,]
                {
                    { 1, 1, "Buckhead", true, "Buckhead Office DDG", null, "buckhead-ddg@atlantafinehomes.com", "buckhead-ddg@atlantafinehomes.com", SourceType.Ddg, 14, StalePolicy.FlagHold, TunnelStatus.Active },
                    { 2, 1, "North Atlanta", true, "North Atlanta Office DDG", null, "northatlanta-ddg@atlantafinehomes.com", "northatlanta-ddg@atlantafinehomes.com", SourceType.Ddg, 14, StalePolicy.FlagHold, TunnelStatus.Active },
                    { 3, 1, "Intown", true, "Intown Office DDG", null, "intown-ddg@atlantafinehomes.com", "intown-ddg@atlantafinehomes.com", SourceType.Ddg, 14, StalePolicy.FlagHold, TunnelStatus.Active },
                    { 4, 1, "Blue Ridge", true, "Blue Ridge Office DDG", null, "blueridge-ddg@atlantafinehomes.com", "blueridge-ddg@atlantafinehomes.com", SourceType.Ddg, 14, StalePolicy.FlagHold, TunnelStatus.Active },
                    { 5, 1, "Cobb", true, "Cobb Office DDG", null, "cobb-ddg@atlantafinehomes.com", "cobb-ddg@atlantafinehomes.com", SourceType.Ddg, 14, StalePolicy.FlagHold, TunnelStatus.Active },
                    { 6, 1, "Clayton", true, "Clayton Office DDG", null, "clayton-ddg@atlantafinehomes.com", "clayton-ddg@atlantafinehomes.com", SourceType.Ddg, 14, StalePolicy.FlagHold, TunnelStatus.Active }
                });
        }
    }
}
