// <auto-generated />
using System;
using AFHSync.Shared.Data;
using AFHSync.Shared.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AFHSync.Api.Migrations
{
    [DbContext(typeof(AFHSyncDbContext))]
    [Migration("20260409235501_AddTunnelContactExclusions")]
    partial class AddTunnelContactExclusions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "run_type", new[] { "dry_run", "manual", "scheduled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "source_type", new[] { "ddg", "mailbox_contacts", "org_contacts" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "stale_policy", new[] { "auto_remove", "flag_hold", "leave" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sync_behavior", new[] { "add_missing", "always", "nosync", "remove_blank" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sync_status", new[] { "cancelled", "failed", "pending", "running", "success", "warning" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "target_scope", new[] { "all_users", "specific_users" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tunnel_status", new[] { "active", "inactive" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AFHSync.Shared.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("app_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sync runs every 4 hours",
                            Key = "sync_schedule_cron",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "0 */4 * * *"
                        },
                        new
                        {
                            Id = 2,
                            Description = "included | separate_pass | disabled",
                            Key = "photo_sync_mode",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "included"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Contacts per batch for Graph writes",
                            Key = "batch_size",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "50"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Concurrent target mailbox processing",
                            Key = "parallelism",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Default stale policy for new tunnels",
                            Key = "stale_policy_default",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "flag_hold"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Default hold period before auto-remove",
                            Key = "stale_hold_days_default",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "14"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Azure AD Tenant ID",
                            Key = "graph_tenant_id",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = ""
                        },
                        new
                        {
                            Id = 8,
                            Description = "Entra App Registration Client ID",
                            Key = "graph_client_id",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = ""
                        },
                        new
                        {
                            Id = 9,
                            Description = "Entra App Registration Client Secret (use Key Vault in production)",
                            Key = "graph_client_secret",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = ""
                        },
                        new
                        {
                            Id = 10,
                            Description = "Photo sync schedule for separate_pass mode (every 6 hours)",
                            Key = "photo_sync_cron",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "0 */6 * * *"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Auto-trigger photo sync after contact sync completes (separate_pass mode)",
                            Key = "photo_sync_auto_trigger",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = "false"
                        });
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.ContactSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_hash");

                    b.Property<string>("GraphContactId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("graph_contact_id");

                    b.Property<bool>("IsStale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_stale");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("LastResult")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_result");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<int>("PhoneListId")
                        .HasColumnType("integer")
                        .HasColumnName("phone_list_id");

                    b.Property<string>("PhotoHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("photo_hash");

                    b.Property<string>("PreviousDataHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_data_hash");

                    b.Property<string>("PreviousPhotoHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_photo_hash");

                    b.Property<int>("SourceUserId")
                        .HasColumnType("integer")
                        .HasColumnName("source_user_id");

                    b.Property<DateTime?>("StaleDetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stale_detected_at");

                    b.Property<int>("TargetMailboxId")
                        .HasColumnType("integer")
                        .HasColumnName("target_mailbox_id");

                    b.Property<int?>("TunnelId")
                        .HasColumnType("integer")
                        .HasColumnName("tunnel_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("IsStale")
                        .HasDatabaseName("idx_contact_sync_state_stale")
                        .HasFilter("is_stale = TRUE");

                    b.HasIndex("PhoneListId")
                        .HasDatabaseName("idx_contact_sync_state_list");

                    b.HasIndex("SourceUserId")
                        .HasDatabaseName("idx_contact_sync_state_source");

                    b.HasIndex("TargetMailboxId")
                        .HasDatabaseName("idx_contact_sync_state_target");

                    b.HasIndex("TunnelId");

                    b.HasIndex("SourceUserId", "PhoneListId", "TargetMailboxId")
                        .IsUnique()
                        .HasDatabaseName("idx_contact_sync_state_composite");

                    b.ToTable("contact_sync_state", (string)null);
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.FieldProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("field_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Standard field sync profile for all office tunnels",
                            IsDefault = true,
                            Name = "Default",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.FieldProfileField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<SyncBehavior>("Behavior")
                        .HasColumnType("sync_behavior")
                        .HasColumnName("behavior");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<int>("FieldProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("field_profile_id");

                    b.Property<string>("FieldSection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("field_section");

                    b.HasKey("Id");

                    b.HasIndex("FieldProfileId", "FieldName")
                        .IsUnique();

                    b.ToTable("field_profile_fields", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Display Name",
                            DisplayOrder = 1,
                            FieldName = "DisplayName",
                            FieldProfileId = 1,
                            FieldSection = "Identity"
                        },
                        new
                        {
                            Id = 2,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "First Name",
                            DisplayOrder = 2,
                            FieldName = "GivenName",
                            FieldProfileId = 1,
                            FieldSection = "Identity"
                        },
                        new
                        {
                            Id = 3,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Last Name",
                            DisplayOrder = 3,
                            FieldName = "Surname",
                            FieldProfileId = 1,
                            FieldSection = "Identity"
                        },
                        new
                        {
                            Id = 4,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Job Title",
                            DisplayOrder = 4,
                            FieldName = "JobTitle",
                            FieldProfileId = 1,
                            FieldSection = "Identity"
                        },
                        new
                        {
                            Id = 5,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Company",
                            DisplayOrder = 5,
                            FieldName = "CompanyName",
                            FieldProfileId = 1,
                            FieldSection = "Identity"
                        },
                        new
                        {
                            Id = 6,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Email",
                            DisplayOrder = 10,
                            FieldName = "EmailAddresses",
                            FieldProfileId = 1,
                            FieldSection = "Contact Info"
                        },
                        new
                        {
                            Id = 7,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Business Phone",
                            DisplayOrder = 11,
                            FieldName = "BusinessPhones",
                            FieldProfileId = 1,
                            FieldSection = "Contact Info"
                        },
                        new
                        {
                            Id = 8,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Mobile Phone",
                            DisplayOrder = 12,
                            FieldName = "MobilePhone",
                            FieldProfileId = 1,
                            FieldSection = "Contact Info"
                        },
                        new
                        {
                            Id = 9,
                            Behavior = SyncBehavior.Nosync,
                            DisplayName = "Fax",
                            DisplayOrder = 13,
                            FieldName = "HomeFax",
                            FieldProfileId = 1,
                            FieldSection = "Contact Info"
                        },
                        new
                        {
                            Id = 10,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Business Street",
                            DisplayOrder = 20,
                            FieldName = "BusinessStreet",
                            FieldProfileId = 1,
                            FieldSection = "Address"
                        },
                        new
                        {
                            Id = 11,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Business City",
                            DisplayOrder = 21,
                            FieldName = "BusinessCity",
                            FieldProfileId = 1,
                            FieldSection = "Address"
                        },
                        new
                        {
                            Id = 12,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Business State",
                            DisplayOrder = 22,
                            FieldName = "BusinessState",
                            FieldProfileId = 1,
                            FieldSection = "Address"
                        },
                        new
                        {
                            Id = 13,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Business Zip",
                            DisplayOrder = 23,
                            FieldName = "BusinessPostalCode",
                            FieldProfileId = 1,
                            FieldSection = "Address"
                        },
                        new
                        {
                            Id = 14,
                            Behavior = SyncBehavior.Nosync,
                            DisplayName = "Home Address",
                            DisplayOrder = 24,
                            FieldName = "HomeAddress",
                            FieldProfileId = 1,
                            FieldSection = "Address"
                        },
                        new
                        {
                            Id = 15,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Office Location",
                            DisplayOrder = 30,
                            FieldName = "OfficeLocation",
                            FieldProfileId = 1,
                            FieldSection = "Organization"
                        },
                        new
                        {
                            Id = 16,
                            Behavior = SyncBehavior.AddMissing,
                            DisplayName = "Department",
                            DisplayOrder = 31,
                            FieldName = "Department",
                            FieldProfileId = 1,
                            FieldSection = "Organization"
                        },
                        new
                        {
                            Id = 17,
                            Behavior = SyncBehavior.Nosync,
                            DisplayName = "Manager",
                            DisplayOrder = 32,
                            FieldName = "Manager",
                            FieldProfileId = 1,
                            FieldSection = "Organization"
                        },
                        new
                        {
                            Id = 18,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Notes",
                            DisplayOrder = 40,
                            FieldName = "PersonalNotes",
                            FieldProfileId = 1,
                            FieldSection = "Extras"
                        },
                        new
                        {
                            Id = 19,
                            Behavior = SyncBehavior.Nosync,
                            DisplayName = "Birthday",
                            DisplayOrder = 41,
                            FieldName = "Birthday",
                            FieldProfileId = 1,
                            FieldSection = "Extras"
                        },
                        new
                        {
                            Id = 20,
                            Behavior = SyncBehavior.Nosync,
                            DisplayName = "Nickname",
                            DisplayOrder = 42,
                            FieldName = "NickName",
                            FieldProfileId = 1,
                            FieldSection = "Extras"
                        },
                        new
                        {
                            Id = 21,
                            Behavior = SyncBehavior.Always,
                            DisplayName = "Contact Photo",
                            DisplayOrder = 50,
                            FieldName = "Photo",
                            FieldProfileId = 1,
                            FieldSection = "Photo"
                        });
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.OrgContactFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<bool>("IsExcluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_excluded");

                    b.Property<string>("OrgContactId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("org_contact_id");

                    b.Property<int>("TunnelId")
                        .HasColumnType("integer")
                        .HasColumnName("tunnel_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("TunnelId", "OrgContactId")
                        .IsUnique()
                        .HasDatabaseName("idx_org_contact_filters_tunnel_contact");

                    b.ToTable("org_contact_filters", (string)null);
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.PhoneList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("contact_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExchangeFolderId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exchange_folder_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<TargetScope>("TargetScope")
                        .HasColumnType("target_scope")
                        .HasColumnName("target_scope");

                    b.Property<string>("TargetUserFilter")
                        .HasColumnType("jsonb")
                        .HasColumnName("target_user_filter");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("user_count");

                    b.HasKey("Id");

                    b.ToTable("phone_lists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactCount = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All AFH and MSIR contacts combined",
                            Name = "All Atlanta Fine Homes",
                            TargetScope = TargetScope.AllUsers,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserCount = 0
                        },
                        new
                        {
                            Id = 2,
                            ContactCount = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All Mountain SIR contacts",
                            Name = "All Mountain",
                            TargetScope = TargetScope.AllUsers,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserCount = 0
                        },
                        new
                        {
                            Id = 3,
                            ContactCount = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "AFH Sotheby's agents only",
                            Name = "AFHSIR",
                            TargetScope = TargetScope.AllUsers,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserCount = 0
                        },
                        new
                        {
                            Id = 4,
                            ContactCount = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mountain SIR contacts only",
                            Name = "MSIR",
                            TargetScope = TargetScope.AllUsers,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserCount = 0
                        },
                        new
                        {
                            Id = 5,
                            ContactCount = 0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gate access codes for Avalon community",
                            Name = "Avalon Gate Code",
                            TargetScope = TargetScope.AllUsers,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserCount = 0
                        });
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.SourceUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_phone");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<string>("EntraId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entra_id");

                    b.Property<string>("ExtensionAttr1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("extension_attr_1");

                    b.Property<string>("ExtensionAttr2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("extension_attr_2");

                    b.Property<string>("ExtensionAttr3")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("extension_attr_3");

                    b.Property<string>("ExtensionAttr4")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("extension_attr_4");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fetched_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MailboxType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mailbox_type");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mobile_phone");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OfficeLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("office_location");

                    b.Property<string>("PhotoHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("photo_hash");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("street_address");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("EntraId")
                        .IsUnique()
                        .HasDatabaseName("idx_source_users_entra");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("idx_source_users_enabled");

                    b.ToTable("source_users", (string)null);
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.SyncRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("ContactsCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("contacts_created");

                    b.Property<int>("ContactsFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("contacts_failed");

                    b.Property<int>("ContactsRemoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("contacts_removed");

                    b.Property<int>("ContactsSkipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("contacts_skipped");

                    b.Property<int>("ContactsUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("contacts_updated");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<bool>("IsDryRun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_dry_run");

                    b.Property<int>("PhotosFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("photos_failed");

                    b.Property<int>("PhotosUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("photos_updated");

                    b.Property<RunType>("RunType")
                        .HasColumnType("run_type")
                        .HasColumnName("run_type");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<SyncStatus>("Status")
                        .HasColumnType("sync_status")
                        .HasColumnName("status");

                    b.Property<int>("ThrottleEvents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("throttle_events");

                    b.Property<int>("TunnelsFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tunnels_failed");

                    b.Property<int>("TunnelsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tunnels_processed");

                    b.Property<int>("TunnelsWarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tunnels_warned");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_sync_runs_started");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_sync_runs_status");

                    b.ToTable("sync_runs", (string)null);
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.SyncRunItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FieldChanges")
                        .HasColumnType("jsonb")
                        .HasColumnName("field_changes");

                    b.Property<int?>("PhoneListId")
                        .HasColumnType("integer")
                        .HasColumnName("phone_list_id");

                    b.Property<int?>("SourceUserId")
                        .HasColumnType("integer")
                        .HasColumnName("source_user_id");

                    b.Property<int>("SyncRunId")
                        .HasColumnType("integer")
                        .HasColumnName("sync_run_id");

                    b.Property<int?>("TargetMailboxId")
                        .HasColumnType("integer")
                        .HasColumnName("target_mailbox_id");

                    b.Property<int?>("TunnelId")
                        .HasColumnType("integer")
                        .HasColumnName("tunnel_id");

                    b.HasKey("Id");

                    b.HasIndex("PhoneListId");

                    b.HasIndex("SourceUserId");

                    b.HasIndex("SyncRunId")
                        .HasDatabaseName("idx_sync_run_items_run");

                    b.HasIndex("TargetMailboxId");

                    b.HasIndex("TunnelId")
                        .HasDatabaseName("idx_sync_run_items_tunnel");

                    b.ToTable("sync_run_items", (string)null);
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.TargetMailbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<string>("EntraId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entra_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("EntraId")
                        .IsUnique()
                        .HasDatabaseName("idx_target_mailboxes_entra");

                    b.ToTable("target_mailboxes", (string)null);
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.Tunnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("FieldProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("field_profile_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("PhotoSyncEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("photo_sync_enabled");

                    b.Property<int>("StaleHoldDays")
                        .HasColumnType("integer")
                        .HasColumnName("stale_hold_days");

                    b.Property<StalePolicy>("StalePolicy")
                        .HasColumnType("stale_policy")
                        .HasColumnName("stale_policy");

                    b.Property<TunnelStatus>("Status")
                        .HasColumnType("tunnel_status")
                        .HasColumnName("status");

                    b.Property<string>("TargetGroupId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_group_id");

                    b.Property<string>("TargetGroupName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_group_name");

                    b.Property<string>("TargetUserEmails")
                        .HasColumnType("text")
                        .HasColumnName("target_user_emails");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("FieldProfileId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_tunnels_status");

                    b.ToTable("tunnels", (string)null);
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.TunnelContactExclusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("EntraId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TunnelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TunnelId", "EntraId")
                        .IsUnique();

                    b.ToTable("tunnel_contact_exclusions", (string)null);
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.TunnelPhoneList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("PhoneListId")
                        .HasColumnType("integer")
                        .HasColumnName("phone_list_id");

                    b.Property<int>("TunnelId")
                        .HasColumnType("integer")
                        .HasColumnName("tunnel_id");

                    b.HasKey("Id");

                    b.HasIndex("PhoneListId");

                    b.HasIndex("TunnelId", "PhoneListId")
                        .IsUnique();

                    b.ToTable("tunnel_phone_lists", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 1,
                            TunnelId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 2,
                            TunnelId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 1,
                            TunnelId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 2,
                            TunnelId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 1,
                            TunnelId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 2,
                            TunnelId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 1,
                            TunnelId = 4
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 2,
                            TunnelId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 1,
                            TunnelId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 2,
                            TunnelId = 5
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 1,
                            TunnelId = 6
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneListId = 2,
                            TunnelId = 6
                        });
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.TunnelSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SourceDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_display_name");

                    b.Property<string>("SourceFilterPlain")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_filter_plain");

                    b.Property<string>("SourceIdentifier")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_identifier");

                    b.Property<string>("SourceSmtpAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("source_smtp_address");

                    b.Property<SourceType>("SourceType")
                        .HasColumnType("source_type")
                        .HasColumnName("source_type");

                    b.Property<int>("TunnelId")
                        .HasColumnType("integer")
                        .HasColumnName("tunnel_id");

                    b.HasKey("Id");

                    b.HasIndex("TunnelId")
                        .HasDatabaseName("idx_tunnel_sources_tunnel_id");

                    b.ToTable("tunnel_sources", (string)null);
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.ContactSyncState", b =>
                {
                    b.HasOne("AFHSync.Shared.Entities.PhoneList", "PhoneList")
                        .WithMany()
                        .HasForeignKey("PhoneListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AFHSync.Shared.Entities.SourceUser", "SourceUser")
                        .WithMany()
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AFHSync.Shared.Entities.TargetMailbox", "TargetMailbox")
                        .WithMany()
                        .HasForeignKey("TargetMailboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AFHSync.Shared.Entities.Tunnel", "Tunnel")
                        .WithMany()
                        .HasForeignKey("TunnelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PhoneList");

                    b.Navigation("SourceUser");

                    b.Navigation("TargetMailbox");

                    b.Navigation("Tunnel");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.FieldProfileField", b =>
                {
                    b.HasOne("AFHSync.Shared.Entities.FieldProfile", "FieldProfile")
                        .WithMany("FieldProfileFields")
                        .HasForeignKey("FieldProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldProfile");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.OrgContactFilter", b =>
                {
                    b.HasOne("AFHSync.Shared.Entities.Tunnel", "Tunnel")
                        .WithMany()
                        .HasForeignKey("TunnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tunnel");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.SyncRunItem", b =>
                {
                    b.HasOne("AFHSync.Shared.Entities.PhoneList", "PhoneList")
                        .WithMany()
                        .HasForeignKey("PhoneListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AFHSync.Shared.Entities.SourceUser", "SourceUser")
                        .WithMany()
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AFHSync.Shared.Entities.SyncRun", "SyncRun")
                        .WithMany("SyncRunItems")
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AFHSync.Shared.Entities.TargetMailbox", "TargetMailbox")
                        .WithMany()
                        .HasForeignKey("TargetMailboxId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AFHSync.Shared.Entities.Tunnel", "Tunnel")
                        .WithMany()
                        .HasForeignKey("TunnelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PhoneList");

                    b.Navigation("SourceUser");

                    b.Navigation("SyncRun");

                    b.Navigation("TargetMailbox");

                    b.Navigation("Tunnel");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.Tunnel", b =>
                {
                    b.HasOne("AFHSync.Shared.Entities.FieldProfile", "FieldProfile")
                        .WithMany("Tunnels")
                        .HasForeignKey("FieldProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FieldProfile");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.TunnelContactExclusion", b =>
                {
                    b.HasOne("AFHSync.Shared.Entities.Tunnel", "Tunnel")
                        .WithMany()
                        .HasForeignKey("TunnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tunnel");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.TunnelPhoneList", b =>
                {
                    b.HasOne("AFHSync.Shared.Entities.PhoneList", "PhoneList")
                        .WithMany("TunnelPhoneLists")
                        .HasForeignKey("PhoneListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AFHSync.Shared.Entities.Tunnel", "Tunnel")
                        .WithMany("TunnelPhoneLists")
                        .HasForeignKey("TunnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhoneList");

                    b.Navigation("Tunnel");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.TunnelSource", b =>
                {
                    b.HasOne("AFHSync.Shared.Entities.Tunnel", "Tunnel")
                        .WithMany("TunnelSources")
                        .HasForeignKey("TunnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tunnel");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.FieldProfile", b =>
                {
                    b.Navigation("FieldProfileFields");

                    b.Navigation("Tunnels");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.PhoneList", b =>
                {
                    b.Navigation("TunnelPhoneLists");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.SyncRun", b =>
                {
                    b.Navigation("SyncRunItems");
                });

            modelBuilder.Entity("AFHSync.Shared.Entities.Tunnel", b =>
                {
                    b.Navigation("TunnelPhoneLists");

                    b.Navigation("TunnelSources");
                });
#pragma warning restore 612, 618
        }
    }
}
